
singleuser:
  image:
    name: "SINGLEUSER_IMAGE_NAME"
    tag: dev
  memory:
    limit: 200M
  cpu:
    limit: 1
  storage:
    # Dynamically allocated user storage is not supported for non-cloud environments!
    #
    # Jupyterhub for k8s expects a storage class to be available that will
    # allocate new Persistent Volumes for each user. This would be fine if we 
    # were using a cloud-based storage class which can dynamically provision
    # new virtual volumes for each user. However, local storage classes
    # behave differently. A local PV is a physical hard disk attached to the node,
    # and dynamic allocation is not supported.
    type: none
#    capacity: 1Gi
#    dynamic:
#      storageClass: standard

debug:
  enabled: true

proxy:
  secretToken: "SECRET"
  service:
    type: NodePort
    nodePorts:
      http: 31212

# Automatically remove user pods that have been inactive for over an hour.
# Check every 10 minutes by default.
cull:
  enabled: true

rbac:
  enabled: true

hub:
  image:
    name: "HUB_IMAGE_NAME"
    tag: dev
  db:
    type: sqlite-memory
  extraVolumes:
    - name: stochss
      hostPath:
        path: "HOST_PATH"
        type: Directory
  extraVolumeMounts:
    - mountPath: /stochss
      name: stochss

  cookieSecret: "SECRET"

  extraConfig: 
    oauth: ""
    stochss: |
      import sys
      sys.path.insert(1, '/stochss')

      c.JupyterHub.log_level = 'DEBUG'

      c.JupyterHub.default_url = '/stochss'

      # Page handlers
      from handlers.pages import HomeHandler, ModelBrowserHandler, ModelEditorHandler, JobEditorHandler

      # File Browser API Handlers
      from handlers.file_browser import \
        ModelBrowserFileList, \
        ModelToNotebookHandler, \
        DeleteFileAPIHandler, \
        MoveFileAPIHandler, \
        DuplicateModelHandler, \
        RenameAPIHandler, \
        ConvertToSpatialAPIHandler, \
        ConvertToModelAPIHandler
        
      # Model API handlers
      from handlers.models import \
        JsonFileAPIHandler, \
        RunModelAPIHandler

      # Job API Handlers
      from handlers.jobs import \
        SaveJobAPIHandler, \
        RunJobAPIHandler, \
        JobInfoAPIHandler, \
        JobStatusAPIHandler, \
        PlotJobResultsAPIHandler

      # Username API Handler
      from handlers.username import UsernameHandler

      # StochSS request handlers
      c.JupyterHub.extra_handlers = [
          # API handlers
          (r"/stochss/api/user\/?", UsernameHandler),
          (r"/stochss/api/json-data/(.+)\/?", JsonFileAPIHandler),
          (r"/stochss/api/models/run/(\w+)/(\w+)?\/?(.+)\/?", RunModelAPIHandler),
          (r"/stochss/api/model/duplicate/(.+)\/?", DuplicateModelHandler),
          (r"/stochss/api/models/to-notebook/(.+)\/?", ModelToNotebookHandler),
          (r"/stochss/api/model/to-spatial/(.+)\/?", ConvertToSpatialAPIHandler),
          (r"/stochss/api/model/to-model/(.+)\/?", ConvertToModelAPIHandler),
          (r"/stochss/api/jobs/save-job/(\w+)\/?(.+)\/?", SaveJobAPIHandler),
          (r"/stochss/api/jobs/run-job/(\w+)\/?(.+)\/?", RunJobAPIHandler),
          (r"/stochss/api/jobs/job-info(.+)\/?", JobInfoAPIHandler),
          (r"/stochss/api/jobs/job-status/(.+)\/?", JobStatusAPIHandler),
          (r"/stochss/api/jobs/plot-results/(.+)\/?", PlotJobResultsAPIHandler),
          (r"/stochss/api/file/move/(.+)\/?", MoveFileAPIHandler),
          (r"/stochss/api/file/delete(.+)\/?", DeleteFileAPIHandler),
          (r"/stochss/api/file/rename/(.+)\/?", RenameAPIHandler),
          # Pages
          (r"/stochss\/?", HomeHandler),
          (r"/stochss/models\/?$", ModelBrowserHandler),
          (r"/stochss/models/browser-list(.+)\/?", ModelBrowserFileList),
          (r"/stochss/models/edit\/?(.+)?\/?", ModelEditorHandler),
          (r"/stochss/jobs/edit\/?(.+)?\/?", JobEditorHandler),
          #(r"/stochss.*", MainHandler)
      ]

      ## Paths to search for jinja templates, before using the default templates.
      c.JupyterHub.template_paths = [
        "/stochss/jupyterhub_templates/",
        "/usr/local/share/jupyterhub/static/stochss/"
      ]

