
singleuser:
  image:
    name: "SINGLEUSER_IMAGE_NAME"
    tag: dev
  memory:
    limit: 200M
    guarantee: 200M
  cpu:
    limit: 1
    guarantee: .3
  storage:
    # Dynamically allocated user storage is not supported for non-cloud environments!
    #
    # Jupyterhub for k8s expects a storage class to be available that will
    # allocate new Persistent Volumes for each user. This would be fine if we 
    # were using a cloud-based storage class which can dynamically provision
    # new virtual volumes for each user. However, local storage classes
    # behave differently. A local PV is a physical hard disk attached to the node,
    # and dynamic allocation is not supported.
    type: none
#    capacity: 1Gi
#    dynamic:
#      storageClass: standard

debug:
  enabled: true

proxy:
  secretToken: "SECRET"
  service:
    type: NodePort
    nodePorts:
      http: 31212

# Remove inactive user pods (set to defaults)
cull:
  timeout: 3600
  every: 600

rbac:
  enabled: true

hub:
  image:
    name: "HUB_IMAGE_NAME"
    tag: dev
  db:
    type: sqlite-memory
  extraVolumes:
    - name: stochss
      hostPath:
        path: "HOST_PATH"
        type: Directory
  extraVolumeMounts:
    - mountPath: /stochss
      name: stochss

  cookieSecret: "SECRET"

  extraConfig: 
    oauth: ""
    stochss: |
      import sys
      sys.path.insert(1, '/stochss')

      c.JupyterHub.log_level = 'DEBUG'

      c.JupyterHub.default_url = '/stochss'

      # Page handlers
      from handlers.pages import HomeHandler, ModelBrowserHandler, ModelEditorHandler, WorkflowEditorHandler

      # File Browser API Handlers
      from handlers.file_browser import \
        ModelBrowserFileList, \
        ModelToNotebookHandler, \
        DeleteFileAPIHandler, \
        MoveFileAPIHandler, \
        DuplicateModelHandler, \
        DuplicateDirectoryHandler, \
        RenameAPIHandler, \
        ConvertToSpatialAPIHandler, \
        ConvertToModelAPIHandler, \
        SBMLToModelAPIHandler, \
        ModelToSBMLAPIHandler, \
        DownloadAPIHandler, \
        CreateDirectoryHandler
        
      # Model API handlers
      from handlers.models import \
        JsonFileAPIHandler, \
        RunModelAPIHandler

      # Workflow API Handlers
      from handlers.workflows import \
        SaveWorkflowAPIHandler, \
        RunWorkflowAPIHandler, \
        WorkflowInfoAPIHandler, \
        WorkflowStatusAPIHandler, \
        PlotWorkflowResultsAPIHandler

      # Username API Handler
      from handlers.username import UsernameHandler

      # StochSS request handlers
      c.JupyterHub.extra_handlers = [
          # API handlers
          (r"/stochss/api/user\/?", UsernameHandler),
          (r"/stochss/api/json-data/(.+)\/?", JsonFileAPIHandler),
          (r"/stochss/api/models/run/(\w+)/(\w+)?\/?(.+)\/?", RunModelAPIHandler),
          (r"/stochss/api/model/duplicate/(.+)\/?", DuplicateModelHandler),
          (r"/stochss/api/models/to-notebook/(.+)\/?", ModelToNotebookHandler),
          (r"/stochss/api/model/to-spatial/(.+)\/?", ConvertToSpatialAPIHandler),
          (r"/stochss/api/model/to-sbml/(.+)\/?", ModelToSBMLAPIHandler),
          (r"/stochss/api/spatial/to-model/(.+)\/?", ConvertToModelAPIHandler),
          (r"/stochss/api/sbml/to-model/(.+)\/?", SBMLToModelAPIHandler),
          (r"/stochss/api/workflow/save-workflow/(\w+)\/?(.+)\/?", SaveWorkflowAPIHandler),
          (r"/stochss/api/workflow/run-workflow/(\w+)\/?(.+)\/?", RunWorkflowAPIHandler),
          (r"/stochss/api/workflow/workflow-info(.+)\/?", WorkflowInfoAPIHandler),
          (r"/stochss/api/workflow/workflow-status/(.+)\/?", WorkflowStatusAPIHandler),
          (r"/stochss/api/workflow/plot-results/(.+)\/?", PlotWorkflowResultsAPIHandler),
          (r"/stochss/api/file/move/(.+)\/?", MoveFileAPIHandler),
          (r"/stochss/api/file/delete(.+)\/?", DeleteFileAPIHandler),
          (r"/stochss/api/file/rename/(.+)\/?", RenameAPIHandler),
          (r"/stochss/api/file/download/(.+)\/?", DownloadAPIHandler),
          (r"/stochss/api/directory/duplicate/(.+)\/?", DuplicateDirectoryHandler),
          (r"/stochss/api/directory/create/(.+)\/?", CreateDirectoryHandler),
          # Pages
          (r"/stochss\/?", HomeHandler),
          (r"/stochss/models\/?$", ModelBrowserHandler),
          (r"/stochss/models/browser-list(.+)\/?", ModelBrowserFileList),
          (r"/stochss/models/edit\/?(.+)?\/?", ModelEditorHandler),
          (r"/stochss/workflow/edit\/?(.+)?\/?", WorkflowEditorHandler),
          #(r"/stochss.*", MainHandler)
      ]

      ## Paths to search for jinja templates, before using the default templates.
      c.JupyterHub.template_paths = [
        "/stochss/jupyterhub_templates/",
        "/usr/local/share/jupyterhub/static/stochss/"
      ]

