kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jhub-admin-role-binding
  namespace: jhub
subjects:
- kind: ServiceAccount
  name: hub
  namespace: jhub
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
