/* URDME model file, automatically generated by pyURDME. */
#include <stdlib.h>
#include <math.h>
#include "propensities.h"
#include <stdio.h>

/* Species names */
__DEFINE_SPECIES__

/* Number of reactions */
#define NR __NUMBER_OF_REACTIONS__  // Depricated, will remove in future version.
#define NUM_REACTIONS __NUMBER_OF_REACTIONS__
#define NUM_SPECIES __NUMBER_OF_SPECIES__
#define NUM_VOXELS __NUMBER_OF_VOXELS__

/* Define DataFunctions */
__DEFINE_DATA_FUNCTIONS__

/* Parameter definitions */
__DEFINE_PARAMETERS__

/* Reaction definitions */
__DEFINE_REACTIONS__

PropensityFun *ALLOC_propensities(void)
{
    PropensityFun *ptr = (PropensityFun *)malloc(sizeof(PropensityFun)*NUM_REACTIONS);
    
__DEFINE_PROPFUNS__
    return ptr;
}

void FREE_propensities(PropensityFun* ptr)
{
    free(ptr);
}

