
hub:
  db:
    type: sqlite-memory
  extraConfig: |
    import os, sys
    os.system("git clone https://github.com/stochss/stochss --branch mg-k8s --single-branch /srv/jupyterhub/stochss")
    
    sys.path.insert(1, '/srv/jupyterhub/stochss')

    c.JupyterHub.log_level = 'DEBUG'

    # Page handlers
    #from handlers.main import MainHandler
    from handlers.pages import HomeHandler, ModelBrowserHandler, ModelEditorHandler

    # API handlers
    from handlers.models import ModelFileAPIHandler, ModelBrowserFileList, ModelToNotebookHandler
    from handlers.username import UsernameHandler
    from handlers.run_models import RunModelAPIHandler

    # StochSS request handlers
    # Trailing slash is optional
    c.JupyterHub.extra_handlers = [
            # API handlers
            (r"/stochss/api/user\/?", UsernameHandler),
            (r"/stochss/api/model-data/(.+)\/?", ModelFileAPIHandler),
            (r"/stochss/api/models/run/(.+)\/?", RunModelAPIHandler),
            (r"/stochss/api/models/to-notebook(.+)\/?", ModelToNotebookHandler),
            # Pages
            (r"/stochss\/?", HomeHandler),
            (r"/stochss/models\/?$", ModelBrowserHandler),
            (r"/stochss/models/browser-list(.+)\/?", ModelBrowserFileList),
            (r"/stochss/models/edit\/?(.+)?\/?", ModelEditorHandler)
            #(r"/stochss.*", MainHandler)
    ]

    ## Paths to search for jinja templates, before using the default templates.
    c.JupyterHub.template_paths = [
      "/srv/jupyterhub/stochss/jupyterhub_templates/",
      "/srv/jupyterhub/stochss/dist/"
      #"/opt/conda/share/jupyterhub/static/stochss/"
    ]


singleuser:
  # very small limits for testing on small instances
  memory:
    guarantee: 100M
    limit: 200M
  cpu:
    guarantee: 0.3
    limit: 1
  storage:
    type: none
#    capacity: 1Gi
#    dynamic:
#      storageClass: standard

debug:
  enabled: true

scheduling:
  userScheduler:
    enabled: true


