application: stochssapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static/ico/favicon.ico
  static_files: static/ico/favicon.ico
  upload: static/ico/favicon.ico
- url: /static
  static_dir: static
- url: /lib/flot
  static_dir: lib/flot

- url: /backend/synchronizedb
  script: backend.backend_handler.app

- url: /backend/queue
  script: backend.backend_handler.app

- url: /.*
  script: stochssapp.app

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest

skip_files:
- ^(.*/)?\.bak$
