name: Ubuntu/Firefox Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Integration Tests
      run: | 
        pip install -r requirements.txt
        cd stochss/tests/integration_tests
        pip install -r requirements.txt
        python run_tests.py
