name: Ubuntu/Firefox Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Move To IT Directory
      run: | 
        cd stochss/tests/integration_tests
        pwd
    - name: Install Dependencies
      run: |
        pwd
        pip install -r requirements.txt
    - name: Run Integration Tests
      run: python run_tests.py
