name: Windows/Firefox Integration Test
on: [push]
jobs:
  build:
        runs-on: macos-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Requirements
      run: | 
        pip install -r requirements.txt
    - name: Install Selenium Requirements
      run: | 
        cd stochss/tests/integration_tests
        pip install -r requirements.txt
    - name: Build Docker Image
      run: make build
    - name: Run Integration Tests
      run: |
        cd stochss/tests/integration_tests 
        python run_tests.py
