name: Ubuntu Integration Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Requirements
      run: | 
        pip install -r requirements.txt
    - name: Install Selenium Requirements
      run: | 
        cd stochss/tests/integration_tests
        pip install -r requirements.txt
    - name: Build Docker Image
      run: make build
    - name: Run Firefox Integration Tests
      run: |
        cd stochss/tests/integration_tests 
        python run_tests.py
    - name: Install Chrome Requirements
      run: | 
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
    - name: Run Chrome Integration Tests
      run: |
        TEST_BROWSER=Chrome
        export TEST_BROWSER
        cd stochss/tests/integration_tests 
        python run_tests.py
