name: Ubuntu/Firefox Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v2
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Requirements
      run: | 
        pip install -r requirements.txt
    - name: Install Selenium Requirements
      run: | 
        cd stochss/tests/integration_tests
        pip install -r requirements.txt
    - name: Disable Google Analytics
      run: |
        echo "127.0.0.1 google-analytics.com www.google-analytics.com ssl.google-analytics.com www.ssl.google-analytics.com statcounter.com www.statcounter.com c.statcounter.com www.c.statcounter.com" | sudo tee -a /etc/hosts
        sudo /etc/init.d/dns-clean restart
    - name: Build Docker Image
      run: make build
    - name: Run Integration Tests
      run: |
        cd stochss/tests/integration_tests 
        python run_tests.py
